Studenti/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace Studenti.Models
{
    public class Student
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        [Display(Name ="Indeks")]
        public string Indeks { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name = "Ime i Prezime")]
        public string ImePrezime { get; set; }
        [Required]
        [StringLength(2)]
        [Display(Name = "Potpis")]
        public string Potpis { get; set; }  

        public ICollection<StudentLab>? Labs { get; set; } = new List<StudentLab>();

    }
}

Studenti/Models/StudentLab.cs
using System.ComponentModel.DataAnnotations;

namespace Studenti.Models
{
    public class StudentLab
    {
        [Key]
        public int Id { get; set; }

        public int StudentId { get; set; }
        public Student? Student { get; set; }
        public int LabVezbaId { get; set; }
        public LabVezba? LabVezba { get; set; }
        [StringLength(2)]
        [Display(Name = "Zavrsena")]
        public string? Zavrsena { get; set; }
        [Display(Name = "Poeni")]
        public int? Poeni { get; set; }
        [Display(Name = "Data na Zavrsuvanje")]
        [DataType(DataType.Date)]
        public DateOnly? DataZavrsuvanje { get; set; }

    }
}

Studenti/Controllers/LabVezbasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;

namespace Studenti.Controllers
{
    public class LabVezbasController : Controller
    {
        private readonly StudentiContext _context;

        public LabVezbasController(StudentiContext context)
        {
            _context = context;
        }

        // GET: LabVezbas
        public async Task<IActionResult> Index(string searchString1, string searchString2)
        {
            var allLabs = await _context.LabVezba.ToListAsync();
            if (!String.IsNullOrEmpty(searchString1))
            {

                allLabs = allLabs.Where(n => n.Naslov.Contains(searchString1, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            if (!String.IsNullOrEmpty(searchString2))
            {

                allLabs = allLabs.Where(n => n.Opis.Contains(searchString2, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            return View(allLabs);
        }

        // GET: LabVezbas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labVezba = await _context.LabVezba
                .FirstOrDefaultAsync(m => m.Id == id);
            if (labVezba == null)
            {
                return NotFound();
            }

            return View(labVezba);
        }

        // GET: LabVezbas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LabVezbas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naslov,Opis")] LabVezba labVezba)
        {
            if (ModelState.IsValid)
            {
                _context.Add(labVezba);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(labVezba);
        }

        // GET: LabVezbas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labVezba = await _context.LabVezba.FindAsync(id);
            if (labVezba == null)
            {
                return NotFound();
            }
            return View(labVezba);
        }

        // POST: LabVezbas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naslov,Opis")] LabVezba labVezba)
        {
            if (id != labVezba.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(labVezba);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LabVezbaExists(labVezba.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(labVezba);
        }

        // GET: LabVezbas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labVezba = await _context.LabVezba
                .FirstOrDefaultAsync(m => m.Id == id);
            if (labVezba == null)
            {
                return NotFound();
            }

            return View(labVezba);
        }

        // POST: LabVezbas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var labVezba = await _context.LabVezba.FindAsync(id);
            if (labVezba != null)
            {
                _context.LabVezba.Remove(labVezba);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LabVezbaExists(int id)
        {
            return _context.LabVezba.Any(e => e.Id == id);
        }

    }
}

Studenti/Controllers/StudentLabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;

namespace Studenti.Controllers
{
    public class StudentLabsController : Controller
    {
        private readonly StudentiContext _context;

        public StudentLabsController(StudentiContext context)
        {
            _context = context;
        }

        // GET: StudentLabs
        public async Task<IActionResult> Index(int id)
        {
            var kolokvium3105Context = _context.StudentLab.Where(s => s.LabVezbaId == id).Include(s => s.LabVezba).Include(s => s.Student);
            return View(await kolokvium3105Context.ToListAsync());
        }

        // GET: StudentLabs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLab = await _context.StudentLab
                .Include(s => s.LabVezba)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentLab == null)
            {
                return NotFound();
            }

            return View(studentLab);
        }

        // GET: StudentLabs/Create
        public IActionResult Create()
        {
            ViewData["LabVezbaId"] = new SelectList(_context.LabVezba, "Id", "Naslov");
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "ImePrezime");
            return View();
        }

        // POST: StudentLabs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,LabVezbaId,Zavrsena,Poeni,DataZavrsuvanje")] StudentLab studentLab)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentLab);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LabVezbaId"] = new SelectList(_context.LabVezba, "Id", "Naslov", studentLab.LabVezbaId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "ImePrezime", studentLab.StudentId);
            return View(studentLab);
        }

        // GET: StudentLabs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLab = await _context.StudentLab.FindAsync(id);
            if (studentLab == null)
            {
                return NotFound();
            }
            ViewData["LabVezbaId"] = new SelectList(_context.LabVezba, "Id", "Naslov", studentLab.LabVezbaId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "ImePrezime", studentLab.StudentId);
            return View(studentLab);
        }

        // POST: StudentLabs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentId,LabVezbaId,Zavrsena,Poeni,DataZavrsuvanje")] StudentLab studentLab)
        {
            if (id != studentLab.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentLab);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentLabExists(studentLab.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LabVezbaId"] = new SelectList(_context.LabVezba, "Id", "Naslov", studentLab.LabVezbaId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "ImePrezime", studentLab.StudentId);
            return View(studentLab);
        }

        // GET: StudentLabs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLab = await _context.StudentLab
                .Include(s => s.LabVezba)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentLab == null)
            {
                return NotFound();
            }

            return View(studentLab);
        }

        // POST: StudentLabs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var studentLab = await _context.StudentLab.FindAsync(id);
            if (studentLab != null)
            {
                _context.StudentLab.Remove(studentLab);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentLabExists(int id)
        {
            return _context.StudentLab.Any(e => e.Id == id);
        }


        //public async Task<IActionResult> Students(int? labVezbaId)
        //{
        //    if (labVezbaId == null)
        //    {
        //        return NotFound();
        //    }

        //    var labVezba = await _context.LabVezba
        //        .Include(l => l.Students)
        //            .ThenInclude(sl => sl.Student)
        //        .FirstOrDefaultAsync(l => l.Id == labVezbaId);

        //    if (labVezba == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(labVezba);
        //}



    }
}

Studenti/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;

namespace Studenti.Controllers
{
    public class StudentsController : Controller
    {
        private readonly StudentiContext _context;

        public StudentsController(StudentiContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _context.Student.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Indeks,ImePrezime,Potpis")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Indeks,ImePrezime,Potpis")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            if (student != null)
            {
                _context.Student.Remove(student);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.Id == id);
        }
    }
}

Studenti/Views/StudentLabs/Create.cshtml
@model Studenti.Models.StudentLab

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentLab</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LabVezbaId" class="control-label"></label>
                <select asp-for="LabVezbaId" class ="form-control" asp-items="ViewBag.LabVezbaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Zavrsena" class="control-label"></label>
                <input asp-for="Zavrsena" class="form-control" />
                <span asp-validation-for="Zavrsena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poeni" class="control-label"></label>
                <input asp-for="Poeni" class="form-control" />
                <span asp-validation-for="Poeni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZavrsuvanje" class="control-label"></label>
                <input asp-for="DataZavrsuvanje" class="form-control" />
                <span asp-validation-for="DataZavrsuvanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Studenti/Views/StudentLabs/Delete.cshtml
@model Studenti.Models.StudentLab

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentLab</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.ImePrezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LabVezba)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LabVezba.Naslov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zavrsena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zavrsena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poeni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poeni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZavrsuvanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZavrsuvanje)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Studenti/Views/StudentLabs/Details.cshtml
@model Studenti.Models.StudentLab

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentLab</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.ImePrezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LabVezba)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LabVezba.Naslov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zavrsena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zavrsena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poeni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poeni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZavrsuvanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZavrsuvanje)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Studenti/Views/StudentLabs/Edit.cshtml
@model Studenti.Models.StudentLab

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentLab</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class="form-control" asp-items="ViewBag.StudentId"></select>
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="LabVezbaId" class="control-label"></label>
                <select asp-for="LabVezbaId" class="form-control" asp-items="ViewBag.LabVezbaId"></select>
                <span asp-validation-for="LabVezbaId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Zavrsena" class="control-label"></label>
                <input asp-for="Zavrsena" class="form-control" />
                <span asp-validation-for="Zavrsena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poeni" class="control-label"></label>
                <input asp-for="Poeni" class="form-control" />
                <span asp-validation-for="Poeni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZavrsuvanje" class="control-label"></label>
                <input asp-for="DataZavrsuvanje" class="form-control" />
                <span asp-validation-for="DataZavrsuvanje" class="text-danger"></span>
            </div>
            <input asp-for="LabVezbaId" hidden />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Studenti/Views/StudentLabs/EditStudentLab.cshtml
@model Studenti.Models.StudentLab

@{
    ViewData["Title"] = "Edit Student Lab Details";
}

<h1>Edit Student Lab Details</h1>

<h4>Student: @Model.Student.ImePrezime</h4>
<h4>Lab Exercise: @Model.LabVezba.Naslov</h4>

<form asp-action="EditStudentLab">
    <div class="form-group">
        <label asp-for="Zavrsena" class="control-label"></label>
        <input asp-for="Zavrsena" class="form-control" />
        <span asp-validation-for="Zavrsena" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Poeni" class="control-label"></label>
        <input asp-for="Poeni" class="form-control" />
        <span asp-validation-for="Poeni" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DataZavrsuvanje" class="control-label"></label>
        <input asp-for="DataZavrsuvanje" class="form-control" />
        <span asp-validation-for="DataZavrsuvanje" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="StudentId" />
    <input type="hidden" asp-for="LabVezbaId" />
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Students" asp-controller="LabVezbas" asp-route-id="@Model.LabVezbaId">Back to List</a>
</div>

Studenti/Views/StudentLabs/Index.cshtml
@model IEnumerable<Studenti.Models.StudentLab>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" >Create New</a>
</p>@* asp-route-id="@Model.FirstOrDefault()?.LabVezbaId" *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LabVezba)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zavrsena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poeni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataZavrsuvanje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Student.ImePrezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LabVezba.Naslov)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zavrsena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Poeni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataZavrsuvanje)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Studenti/Views/StudentLabs/Students.cshtml
@model Studenti.Models.LabVezba

@{
    ViewData["Title"] = "Students in Lab Exercise";
}

<h1>@Model.Naslov</h1>
<h2>@Model.Opis</h2>

<table class="table">
    <thead>
        <tr>
            <th>Student Name</th>
            <th>Index</th>
            <th>Completed</th>
            <th>Points</th>
            <th>Completion Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var studentLab in Model.Students)
        {
            <tr>
                <td>@studentLab.Student.ImePrezime</td>
                <td>@studentLab.Student.Indeks</td>
                <td>@studentLab.Zavrsena</td>
                <td>@studentLab.Poeni</td>
                <td>@studentLab.DataZavrsuvanje?.ToString("yyyy-MM-dd")</td>
                <td>
                    <a asp-action="EditStudentLab" asp-controller="StudentLabs" asp-route-id="@studentLab.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>